server:
  port: 8085

spring:
  application:
    name: notification-service
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always