server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/auth/**
            - id: order-service
              uri: ${ORDER_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/orders/**
            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/products/**
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI:http://localhost:8083}
              predicates:
                - Path=/transactions/**
  application:
    name: gateway-service
  config:
    import: "configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234}

logging:
  level:
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG