spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:/configs,classpath:/configs
        overrides:
          management.opentelemetry.tracing.export.otlp.endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
          management.opentelemetry.logging.export.otlp.endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
  profiles:
    active: native
server:
  port: 8888